<template>
  <div id="home-file" >
      <b-container  fluid="sm" >
        <br />
        <br />
        <br />
        <br />
        <b-row class="text-left">
            <b-col ><h1 >Hello, I'm <span >MONTHON INTRARAPRASIT</span>.</h1></b-col>
        </b-row>
        <br />
        <b-row class="text-left">
            <b-col><h1 >I'm a <span >ARTIFICIAL INTELLIGENCE RESEARCHER</span>.</h1></b-col>
        </b-row>
        <br />
        <br />
        <br />
        <br />
        <b-row class="text-right">
            <b-col ><img class="img-s" src="@/assets/imgtest3.png"/> </b-col>
        </b-row>
        
      </b-container>
  </div>
</template>>

<script>
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'
export default {
  name: 'home-file'
}
</script>

<style scoped>

img {
  max-width: 70%;
  height: auto;
}
.font-home {
  font-style: oblique;
}

.height-full {
  height: 100vh;
}

.bg-dark {
  background-color: #333;
  color: #fff;
}

/* #nav-bar{
  background-color: #ffeb3b;
}
#list-botton{
  color: black;
  font-size: 150%;
}
.navbar-toggler{
  border-color: #ffeb3b!important;
  outline: 0;
  box-shadow: none!important;
}
.navbar-toggler[aria-expanded="true"]{
  background-color: #ffbb1e;
}

#list-botton:hover{
  color: #707070;
}

.nav-link{
  color: black!important;
}
.nav-link:hover{
  color: #707070!important;
} */
</style>
