about<template>
  <div id="port-file">
      <h1>Port Page</h1>
  </div>
</template>>

<script>
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'
export default {
  name: 'port-file'
}
</script>

<style scoped>
/* #nav-bar{
  background-color: #ffeb3b;
}
#list-botton{
  color: black;
  font-size: 150%;
}
.navbar-toggler{
  border-color: #ffeb3b!important;
  outline: 0;
  box-shadow: none!important;
}
.navbar-toggler[aria-expanded="true"]{
  background-color: #ffbb1e;
}

#list-botton:hover{
  color: #707070;
}

.nav-link{
  color: black!important;
}
.nav-link:hover{
  color: #707070!important;
} */
</style>
